# Generated by Django 3.1.5 on 2021-01-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('Cs', 'Cs'), ('It', 'It'), ('General', 'General')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='level',
            field=models.CharField(blank=True, choices=[('level 1', 'level 1'), ('level 2', 'level 2'), ('level 3', 'level 3'), ('level 4', 'level 4')], max_length=30, null=True),
        ),
    ]
