# Generated by Django 3.1.5 on 2021-01-14 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210114_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='ver',
        ),
    ]
