# Generated by Django 3.1.5 on 2021-01-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_studentprofile_ver'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.IntegerField(blank=True, null=True)),
                ('firstName', models.CharField(blank=True, max_length=150, null=True)),
                ('level', models.CharField(blank=True, max_length=30, null=True)),
                ('department', models.CharField(blank=True, max_length=30, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
