# Generated by Django 3.1.5 on 2021-01-26 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_studentattendence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendence',
            name='department',
        ),
        migrations.RemoveField(
            model_name='studentattendence',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='studentattendence',
            name='level',
        ),
        migrations.RemoveField(
            model_name='studentattendence',
            name='studentId',
        ),
        migrations.AddField(
            model_name='studentattendence',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.studentprofile'),
        ),
    ]
